name: scope_demo
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  scoped_model: ^0.3.0
  sqflite: ^0.12.1
  path_provider: ^0.4.1
  flutter_screenutil: ^0.4.2
  http:
  sweetalert: ^0.0.1
  liquid_pull_to_refresh: ^1.1.1
  auto_size_text: ^1.0.0
  share: ^0.6.0+1
  flutter_slidable: "^0.4.9"
  url_launcher: ^5.4.2
  flutter_svg: ^0.17.3+1
  material_design_icons_flutter: ^3.2.3895
  flutter_localizations:
    sdk: flutter
  intl:
  intl_translation:
  dio: ^2.1.3
  shared_preferences: ^0.5.6
  fluttertoast: ^3.1.3
  image_picker: ^0.6.4
  provider: ^4.0.4
  path: ^1.6.4

dev_dependencies:
  flutter_test:
    sdk: flutter

sweetalert: any

flutter:
  assets:
    - assets/
    - assets/svgs/
    - assets/images/united-states-of-america.png
    - assets/images/united-arab-emirates.png
    - assets/images/spain.png
    - assets/images/hindi.png
    - assets/images/malayalam.png
    - assets/images/china.png
    - i18n/ar.json
    - i18n/en.json
    - i18n/es.json
    - i18n/hi.json
    - i18n/ml.json
    - i18n/zh.json

  uses-material-design: true

  fonts:
    - family: light
      fonts:
        - asset: fonts/light.ttf
    - family: MyFlutterApp
      fonts:
        - asset: assets/MyFlutterApp.ttf
    - family: MyFlutterApp2
      fonts:
        - asset: assets/MyFlutterApp2.ttf


analyzer:
  language:
    enableSuperMixins: true
