/// Flutter icons MyFlutterApp
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MyFlutterApp
///      fonts:
///       - asset: fonts/MyFlutterApp.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class MyFlutterApp {
  MyFlutterApp._();

  static const _kFontFam = 'MyFlutterApp';

  static const IconData icon = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData qst_details_1 = const IconData(0xe801, fontFamily: _kFontFam);
  static const IconData comments = const IconData(0xe802, fontFamily: _kFontFam);
  static const IconData controbution = const IconData(0xe803, fontFamily: _kFontFam);
  static const IconData cup = const IconData(0xe804, fontFamily: _kFontFam);
  static const IconData estitla3at = const IconData(0xe805, fontFamily: _kFontFam);
  static const IconData icon_1 = const IconData(0xe806, fontFamily: _kFontFam);
  static const IconData lock = const IconData(0xe807, fontFamily: _kFontFam);
  static const IconData logout = const IconData(0xe808, fontFamily: _kFontFam);
  static const IconData meeting = const IconData(0xe809, fontFamily: _kFontFam);
  static const IconData points_system = const IconData(0xe80a, fontFamily: _kFontFam);
  static const IconData qst_details = const IconData(0xe80b, fontFamily: _kFontFam);
  static const IconData qst_related = const IconData(0xe80c, fontFamily: _kFontFam);
  static const IconData seen = const IconData(0xe80d, fontFamily: _kFontFam);
  static const IconData settings = const IconData(0xe80e, fontFamily: _kFontFam);
  static const IconData shield = const IconData(0xe80f, fontFamily: _kFontFam);
  static const IconData university = const IconData(0xe810, fontFamily: _kFontFam);
  static const IconData stars = const IconData(0xe811, fontFamily: _kFontFam);
  static const IconData user = const IconData(0xe812, fontFamily: _kFontFam);
}
